version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Prepare keystore
          command: mkdir -p ~/.droid && 
            echo "keystore=${KEYSTORE}" > ~/.droid/maoni-keystore.properties && 
            echo "storePassword=${STORE_PASSWORD}" >> ~/.droid/maoni-keystore.properties && 
            echo "keyAlias=${KEY_ALIAS}" >> ~/.droid/maoni-keystore.properties && 
            echo "keyPassword=${KEY_PASSWORD}" >> ~/.droid/maoni-keystore.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "maoni-sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "maoni-sample/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Assemble package
          command: ./gradlew clean assembleDebug --stacktrace
      - store_artifacts:
          path: maoni-sample/build/reports
          destination: reports
      - store_test_results:
          path: maoni-sample/build/test-results
